FROM golang:1.11 as builder
LABEL maintainer="Nils Petzall <nils.petzall@gmail.com>"

RUN go get github.com/nats-io/nats.go/

WORKDIR /go/src/github.com/nats-io/nats.go/examples/nats-sub

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w' -o /go/bin/nats-sub *.go

#### FINAL IMAGE ####
FROM scratch

COPY --from=builder /go/bin/nats-sub /nats-sub

ENTRYPOINT ["/nats-sub"]
